var listData = {};
listData.listData00= {
	"success":"ok",
	"data":{
		"pageStart":0,
		"pageSize":6,
		"count":17,
		"list":[{
			"class":"focus",
			"coverImg":"imgs/13.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":1,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/09.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"8个回答",
			"content":"自动化专业的，能学哪些软件对就业有利？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":2,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":3,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":4,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":5,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":6,
			"feilei":"最新",
			},
		]
	}
}

listData.listData01= {
	"success":"ok",
	"data":{
		"pageStart":1,
		"pageSize":6,
		"count":17,
		"list":[{
			"class":"focus",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":1,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":" ",
			"laizi":"来自",
			"from":"性能测试",
			"awn":"0个回答",
			"content":"[国产PLC]耐特生产PLC在铅酸电池固化烘干室PLC控制系统上的功能特点",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":2,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":3,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":" ",
			"laizi":"来自",
			"from":"性能测试",
			"awn":"0个回答",
			"content":"[国产PLC]耐特生产PLC在铅酸电池固化烘干室PLC控制系统上的功能特点",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":4,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":5,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":" ",
			"laizi":"来自",
			"from":"性能测试",
			"awn":"0个回答",
			"content":"[国产PLC]耐特生产PLC在铅酸电池固化烘干室PLC控制系统上的功能特点",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":6,
			"feilei":"最新",
			}
		]
	}
}

listData.listData02= {
	"success":"ok",
	"data":{
		"pageStart":2,
		"pageSize":6,
		"count":17,
		"list":[{
			"class":"focus",
			"coverImg":"imgs/09.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"8个回答",
			"content":"自动化专业的，能学哪些软件对就业有利？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":1,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":2,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":3,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":4,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":5,
			"feilei":"最新",
			},
		]
	}
}