var listData = {};
listData= {
	"success":"ok",
	"data":{
		"count":19,
		"list":[{
			"title":"【优惠倒计时】剑指Java面试-Offer直通车",
			"describe":"159浏览·0推荐·0评论",
			"coverImg":"img/a1.jpg",
			"origin":"原创",
			"sysId":1,
			"articleFl":"推荐",
			},{
			"title":"利用 Kubeadm部署 Kubernetes 1.13.1 集群实践",
			"describe":"170浏览·1推荐·0评论",
			"coverImg":"img/a2.jpg",
			"origin":"原创",
			"sysId":2,
			"articleFl":"推荐",
			},{
			"title":"在 Go 中恰到好处的内存对齐",
			"describe":"104浏览·1推荐·0评论",
			"coverImg":" ",
			"origin":" ",
			"number":"1",
			"number1":"2",
			"sysId":3,
			"articleFl":"推荐",
			},{
			"title":"setNeedsDisplay看我就懂！",
			"describe":"96浏览·0推荐·0评论",
			"coverImg":" ",
			"origin":"原创",
			"number1":"2",
			"sysId":4,
			"articleFl":"推荐",
			},{
			"title":"良心推荐【PHP学习路线】，小白福利，轻松迈进就业门！",
			"describe":"3466浏览·42推荐·7评论",
			"coverImg":"img/a3.jpg",
			"origin":"原创",
			"sysId":5,
			"articleFl":"推荐",
			},{
			"title":"投稿011期 | 寒潮来了，春天还会远嘛？",
			"describe":"65浏览·4推荐·1评论",
			"coverImg":"img/a4.jpg",
			"origin":" ",
			"number":"1",
			"sysId":6,
			"articleFl":"推荐",
			},{
			"title":"从零讲解搭建一个NIO消息服务端",
			"describe":"176浏览·0推荐·0评论",
			"coverImg":"img/a5.jpg",
			"origin":"原创",
			"articleFl":"推荐",
			"sysId":7,
			},{
			"title":"时间轴、纯js日历特效",
			"describe":"497浏览·5推荐·0评论",
			"coverImg":"img/a6.jpg",
			"origin":" ",
			"number":"1",
			"sysId":8,
			"articleFl":"推荐",
			},{
			"title":"当我们在说事件驱动的时候，我们在说什么(翻译)",
			"describe":"259浏览·2推荐·0评论",
			"coverImg":" ",
			"origin":"原创",
			"number1":"2",
			"sysId":9,
			"articleFl":"推荐",
			},{
			"title":"史上最快Docker入门实战! (二) - Docker环境的搭建方法",
			"describe":"244浏览·0推荐·0评论",
			"coverImg":" ",
			"origin":"原创",
			"number1":"2",
			"sysId":10,
			"articleFl":"推荐",
			},{
			"title":"Java 字节的常用封装",
			"describe":"428浏览·7推荐·0评论",
			"coverImg":"img/a7.jpg",
			"origin":" ",
			"number":"1",
			"sysId":11,
			"articleFl":"推荐",
			},{
			"title":"上新+双重优惠 | Spring Boot微服务专栏给你不一样的惊喜！",
			"describe":"500浏览·5推荐·0评论",
			"coverImg":"img/a8.jpg",
			"origin":"原创",
			"sysId":12,
			"articleFl":"推荐",
			},{
			"title":"收发数据的原理(下)",
			"describe":"310浏览·1推荐·0评论",
			"coverImg":"img/a9.jpg",
			"origin":" ",
			"number":"1",
			"sysId":13,
			"articleFl":"推荐",
			},{
			"title":"Netty入门",
			"describe":"213浏览·0推荐·0评论",
			"coverImg":"img/a10.jpg",
			"origin":" ",
			"number":"1",
			"sysId":14,
			"articleFl":"推荐",
			},{
			"title":"【深度学习】反向传播算法——原理介绍与推导（最强版）",
			"describe":"136浏览·2推荐·0评论",
			"coverImg":" ",
			"origin":" ",
			"number":"1",
			"number1":"2",
			"sysId":15,
			"articleFl":"推荐",
			},{
			"title":"Python学习笔记-基础篇(22)-Python日志使用示例",
			"describe":"152浏览·1推荐·0评论",
			"coverImg":"img/a11.jpg",
			"origin":" ",
			"number":"1",
			"sysId":16,
			"articleFl":"推荐",
			},{
			"title":"Eruda 一个移动端调试神器",
			"describe":"48浏览·2推荐·0评论",
			"coverImg":"img/a12.jpg",
			"origin":"原创",
			"sysId":17,
			"articleFl":"推荐",
			},{
			"title":"『React Navigation 3x系列教程』之createBot",
			"describe":"268浏览·3推荐·0评论",
			"coverImg":"img/a25.jpg",
			"origin":" ",
			"number":"1",
			"sysId":18,
			"articleFl":"推荐",
			},{
			"title":"Mac OS 下安装 Vagrant",
			"describe":"137浏览·3推荐·0评论",
			"coverImg":"img/a15.jpg",
			"origin":"原创",
			"sysId":19,
			"articleFl":"推荐",
			},{
			"title":"微信公众号运营推广全文详解分享",
			"describe":"27浏览·0推荐·0评论",
			"coverImg":"  ",
			"origin":" ",
			"number":"1",
			"number1":"2",
			"sysId":20,
			"articleFl":"资讯",
			},{
			"title":"“被狗啃”的按钮引发的开源社区信任危机",
			"describe":"66浏览·0推荐·1评论",
			"coverImg":"  ",
			"origin":"原创",
			"number":" ",
			"number1":"2",
			"sysId":21,
			"articleFl":"资讯",
			},{
			"title":"2018年你们最爱的编程语言发生了什么有趣变化？",
			"describe":"112浏览·1推荐·1评论",
			"coverImg":"img/a16.jpg",
			"origin":" ",
			"number":"1",
			"number1":" ",
			"sysId":22,
			"articleFl":"资讯",
			},{
			"title":"投稿011期 | 工作之择：去远方还是留家乡",
			"describe":"1161浏览·8推荐·5评论",
			"coverImg":"img/a10.jpg",
			"origin":" ",
			"number":"1",
			"number1":" ",
			"sysId":23,
			"articleFl":"资讯",
			},{
			"title":"搭建直播平台过程中的全能“辅助”——流媒体服务器",
			"describe":"110浏览·1推荐·1评论",
			"coverImg":" ",
			"origin":" ",
			"number":"1",
			"number1":"2",
			"sysId":24,
			"articleFl":"资讯",
			},{
			"title":"一对一直播业务具备的四点优势",
			"describe":"71浏览·0推荐·0评论",
			"coverImg":" ",
			"origin":" ",
			"number":"1",
			"number1":"2",
			"sysId":25,
			"articleFl":"资讯",
			},{
			"title":"“Material Design”设计规范在 ComponentOne",
			"describe":"112浏览·1推荐·1评论",
			"coverImg":"img/a7.jpg",
			"origin":"原创",
			"number":" ",
			"number1":" ",
			"sysId":26,
			"articleFl":"资讯",
			},{
			"title":"【Visual Studio 扩展工具】使用 ComponentOne",
			"describe":"112浏览·1推荐·1评论",
			"coverImg":"img/a6.jpg",
			"origin":"原创",
			"number":" ",
			"number1":" ",
			"sysId":27,
			"articleFl":"资讯",
			},{
			"title":"http代理ip:爬虫的基本原理？",
			"describe":"100浏览·1推荐·1评论",
			"coverImg":"img/a6.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":28,
			"articleFl":"资讯",
			},{
			"title":"ActiveReports 大数据分析报告：贸易争端与中国企业数字化转",
			"describe":"100浏览·1推荐·1评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":29,
			"articleFl":"资讯",
			},{
			"title":"Java List",
			"describe":"148浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":30,
			"articleFl":"资讯",
			},{
			"title":"Android短视频开发都需要什么技术？",
			"describe":"258浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":31,
			"articleFl":"资讯",
			},{
			"title":"ActiveReports 大数据分析报告：公交车司乘冲突引发的刑事案",
			"describe":"190浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":32,
			"articleFl":"资讯",
			},{
			"title":"错过了马化腾和马云，雷军这一次仅用4年，打造了一个43亿独角兽",
			"describe":"258浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":33,
			"articleFl":"资讯",
			},{
			"title":"商汤用神木策略，变全球估值最高 AI 霸主",
			"describe":"258浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":34,
			"articleFl":"资讯",
			},{
			"title":"CLOUDSEC 2018 趋势科技布局 AI，全方位抵御资安威胁进击",
			"describe":"258浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":35,
			"articleFl":"资讯",
			},{
			"title":"android8.0适配问题",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a17.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":36,
			"articleFl":"最新文章",
			},{
			"title":"Java：多态乃幸福本源",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a18.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"程序员年底众生相",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a19.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":38,
			"articleFl":"最新文章",
			},{
			"title":"Java接口的实例应用：致敬我的偶像——何塞·穆里尼奥",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a20.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"29岁了还一事无成是人生的常态？",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a21.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"Java的内部类真的那么难以理解？",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a22.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"Linux Mint 18 将拥有自己的应用集",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a23.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"大厂OPPO面试— Android 开发技术面总结",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a24.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"Docker 入门资料收集",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a25.jpg",
			"origin":"原创",
			"number":"1",
			"number1":" ",
			"sysId":37,
			"articleFl":"最新文章",
			},{
			"title":"消失的线程",
			"describe":"5浏览·0推荐·0评论",
			"coverImg":"img/a25.jpg",
			"origin":"原创",
			"number":"1",
			"number1":"2",
			"sysId":37,
			"articleFl":"最新文章",
			}
		]
	}
}