var listData = {};
listData= {
	"success":"ok",
	"data":{
		"count":5,
		"list":[{
			"class":"focus",
			"coverImg":"imgs/09.jpg",
			"laizi":"来自",
			"from":"ThinkPHP",
			"awn":"1个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":1,
			},{
			"class":"great",
			"coverImg":"imgs/01.jpg",
			"laizi":"来自",
			"from":"AngularJS Html/CSS JavaScript",
			"awn":"140个回答",
			"content":"【有奖问答】与大咖交流前端JS与框架开发，免费赢取前端图书（11.28-12.4）",
			"tip":"最赞的回答",           
			"answer":"我觉得不管学习哪门语言，到后面总还是要学习一下规范，程序员的素养必不可少啊！！",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":2,
			},{
			"class":"great",
			"coverImg":"imgs/02.jpg",
			"laizi":"来自",
			"from":"C++ iOS JAVA",
			"awn":"316个回答",
			"content":"各位猿或者媛，一般几点睡啊。有时忍住头痛看java到很晚，第二天就头痛一整天",
			"tip":"已采纳的回答",
			"answer":"没有什么事情是需要熬夜完成的",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":3,
			},{
			"class":"great",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"java",
			"awn":"199个回答",
			"content":"java好学吗.??pp",
			"tip":"最赞的回答",
			"answer":"挺好的",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":4,
			},{
			"class":"great",
			"coverImg":"imgs/04.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"话说，大家想编程的最初初衷是什么",
			"tip":"已采纳的回答",
			"answer":"说兴趣的话有没有人打我....	",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":5,
			},{
			"class":"great",
			"coverImg":"imgs/05.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"为啥要做程序员，初心是什么？",
			"tip":"已采纳的回答",
			"answer":"为啥要做程序员，初心是什么？",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":6,
			},{
			"class":"great",
			"coverImg":"imgs/04.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"遇见好答案---Python编程问答专场",
			"tip":"最赞的回答",
			"answer":"@刘硕老师 我现在在做一些简单的项目，一般用的就是python，本来以前c++用的比较多，现在用过python之后觉得python真的很简单，很简单而且不容易出错，我现在就是做的主要是类似爬虫的探测工作，以及探测得到的数据的比较和存储，虽然没怎么用到那些各种各样的库以及装饰器之类的看起来高大上的东西，但是我用的还是挺(｡･∀･)ﾉﾞ嗨的。其次，我还曾经试着搭建过hadoop的环境，但是mapreduce程序使用python写的因为简单。下面是我的问题1、我这样用合适吗，2、我有个同学跟我说他们做爬虫用java说python不稳定，是这样的吗，我需要注意些什么3、虽然用的很多，心里还是挺没底的，我对底层了解的并不深入，这么简单，会不会有什么后顾之忧。4、Python的最适合做的是什么。    顺便说一下我的理解，我觉得语言不是那么重要，只要能实现相对应的功能就可以了，但是现在好多问题好像都有主流的语言，比如hadoop用java，opencv应C++，这不是主要的，关键是处理的速度与用户感受还有思想。",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":7,
			},{
			"class":"great",
			"coverImg":" ",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"我现在上高一学习编程要怎么学？要先学什么?",
			"tip":"已采纳的回答",
			"answer":"学泡妞，学什么编程",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":8,
			},{
			"class":"great",
			"coverImg":"imgs/05.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"学前端是先学JS还是先学jQuery？",
			"tip":"已采纳的回答",
			"answer":"js是语言，jQ是基于js的轻量级框架，学习顺序自然是先学js，就像四则运算和一元一次方程，你一定不会先学方程吧。还有如果你要搞前端的话，除了要学jQ，目前很热门也很好用的框架angular是很值得学习的！配合jQ的学习，相信你一定能成为优秀的前端工程师！",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":9,
			},{
			"class":"great",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"【花式填坑第4期】如何成长为合格的Java架构师",
			"tip":"最赞的回答",
			"answer":"老师 学习了Java有段时间了 用java工作也快1年了吧    现在有时候也学习其他的语言 学习其他语言的时候 感觉java是一门古董语言 很多语法糖都不怎么好用 而且java更新速度也蛮慢的吧  而且随着人工智能的兴起  Python现在大火  而node也异常火爆  网上说以后做web  可能只剩下一门语言  那就是js  我其实觉得蛮有道理的  不知道老师怎么看 还有 准备学习一门第二语言 老师推荐什么语言啊     哦哦 Google io大会最近将 Kotlin 推荐为android开发默认语言  这个会对java有大影响吗   问题比较多    还请老师原谅	",
			"fa":"我要回答",
			"text":"关注",
			"feilei":"推荐",
			"sysId":10,
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"C PHP Python",
			"awn":"470个回答",
			"content":"为啥要做程序员，初心是什么？",
			"tip":"已采纳的回答",
			"answer":"为啥要做程序员，初心是什么？",
			"fa":"我要回答",
			"text":"关注",
			"sysId":11,
			"feilei":"推荐",
			},{
			"class":"focus",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":12,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":" ",
			"laizi":"来自",
			"from":"性能测试",
			"awn":"0个回答",
			"content":"[国产PLC]耐特生产PLC在铅酸电池固化烘干室PLC控制系统上的功能特点",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":13,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/11.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"8个回答",
			"content":"自动化专业的，能学哪些软件对就业有利？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":14,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/12.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":15,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/13.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":16,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/09.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"8个回答",
			"content":"自动化专业的，能学哪些软件对就业有利？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":17,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":18,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":19,
			"feilei":"最新",
			},{
			"class":"great",
			"coverImg":"imgs/08.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"求大神告诉我考试题！！ 不要太久 写一点回答一点",
			"tip":"已采纳回答",
			"answer":"你是真的不要脸啊。。。。	",
			"fa":"我要回答",
			"text":"关注",
			"sysId":20,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/07.jpg",
			"laizi":"来自",
			"from":"测试",
			"awn":"16个回答",
			"content":"小学毕业的我 能学好软件测试？",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":21,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":"imgs/03.jpg",
			"laizi":"来自",
			"from":"JAVA",
			"awn":"0个回答",
			"content":"PhpStorm 2018.2.6 的controller/index.php问题",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":12,
			"feilei":"最新",
			},{
			"class":"focus",
			"coverImg":" ",
			"laizi":"来自",
			"from":"性能测试",
			"awn":"0个回答",
			"content":"[国产PLC]耐特生产PLC在铅酸电池固化烘干室PLC控制系统上的功能特点",
			"tip":" ",
			"answer":"  ",
			"fa":"我要回答",
			"text":"关注",
			"sysId":13,
			"feilei":"最新",
			},
		]
	}
}